from MainUI import *
from InitialUI import *
from ChooseWalletUI import *
from AddressUI import *
from AddContactUI import *
from BlockInfoUI import *
from AboutUI import *
from SignVerifyUI import *
from EncryptUI import *