# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Main.ui'
#
# Created: Sun May 10 23:32:01 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 589)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/windowIcon/coinami.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.infoTab = QtGui.QWidget()
        self.infoTab.setObjectName(_fromUtf8("infoTab"))
        self.label_5 = QtGui.QLabel(self.infoTab)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 211, 18))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.infoAddressText = QtGui.QLabel(self.infoTab)
        self.infoAddressText.setGeometry(QtCore.QRect(230, 10, 541, 18))
        self.infoAddressText.setObjectName(_fromUtf8("infoAddressText"))
        self.label_7 = QtGui.QLabel(self.infoTab)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 211, 18))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.infoBalanceText = QtGui.QLabel(self.infoTab)
        self.infoBalanceText.setGeometry(QtCore.QRect(230, 40, 541, 18))
        self.infoBalanceText.setObjectName(_fromUtf8("infoBalanceText"))
        self.label_9 = QtGui.QLabel(self.infoTab)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 211, 18))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.infoMineText = QtGui.QLabel(self.infoTab)
        self.infoMineText.setGeometry(QtCore.QRect(230, 70, 541, 18))
        self.infoMineText.setObjectName(_fromUtf8("infoMineText"))
        self.label_11 = QtGui.QLabel(self.infoTab)
        self.label_11.setGeometry(QtCore.QRect(10, 100, 211, 18))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.infoSpendText = QtGui.QLabel(self.infoTab)
        self.infoSpendText.setGeometry(QtCore.QRect(230, 100, 541, 18))
        self.infoSpendText.setObjectName(_fromUtf8("infoSpendText"))
        self.infoReceivedText = QtGui.QLabel(self.infoTab)
        self.infoReceivedText.setGeometry(QtCore.QRect(230, 130, 541, 18))
        self.infoReceivedText.setObjectName(_fromUtf8("infoReceivedText"))
        self.label_14 = QtGui.QLabel(self.infoTab)
        self.label_14.setGeometry(QtCore.QRect(10, 130, 211, 18))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.infoTab)
        self.label_15.setGeometry(QtCore.QRect(10, 170, 211, 18))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.infoFilterButton = QtGui.QPushButton(self.infoTab)
        self.infoFilterButton.setGeometry(QtCore.QRect(670, 160, 97, 27))
        self.infoFilterButton.setObjectName(_fromUtf8("infoFilterButton"))
        self.infoTxTable = QtGui.QTableView(self.infoTab)
        self.infoTxTable.setGeometry(QtCore.QRect(7, 200, 771, 311))
        self.infoTxTable.setObjectName(_fromUtf8("infoTxTable"))
        self.tabWidget.addTab(self.infoTab, _fromUtf8(""))
        self.sendTab = QtGui.QWidget()
        self.sendTab.setObjectName(_fromUtf8("sendTab"))
        self.sendButton = QtGui.QPushButton(self.sendTab)
        self.sendButton.setGeometry(QtCore.QRect(270, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sendButton.setFont(font)
        self.sendButton.setStyleSheet(_fromUtf8(""))
        self.sendButton.setObjectName(_fromUtf8("sendButton"))
        self.sendAddressEdit = QtGui.QLineEdit(self.sendTab)
        self.sendAddressEdit.setGeometry(QtCore.QRect(20, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sendAddressEdit.setFont(font)
        self.sendAddressEdit.setStyleSheet(_fromUtf8(""))
        self.sendAddressEdit.setText(_fromUtf8(""))
        self.sendAddressEdit.setObjectName(_fromUtf8("sendAddressEdit"))
        self.sendCoinsEdit = QtGui.QLineEdit(self.sendTab)
        self.sendCoinsEdit.setGeometry(QtCore.QRect(20, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sendCoinsEdit.setFont(font)
        self.sendCoinsEdit.setStyleSheet(_fromUtf8(""))
        self.sendCoinsEdit.setText(_fromUtf8(""))
        self.sendCoinsEdit.setObjectName(_fromUtf8("sendCoinsEdit"))
        self.sendBalanceLabel = QtGui.QLabel(self.sendTab)
        self.sendBalanceLabel.setGeometry(QtCore.QRect(20, 160, 141, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sendBalanceLabel.setFont(font)
        self.sendBalanceLabel.setStyleSheet(_fromUtf8(""))
        self.sendBalanceLabel.setObjectName(_fromUtf8("sendBalanceLabel"))
        self.sendBalanceText = QtGui.QLabel(self.sendTab)
        self.sendBalanceText.setGeometry(QtCore.QRect(180, 160, 581, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sendBalanceText.setFont(font)
        self.sendBalanceText.setStyleSheet(_fromUtf8(""))
        self.sendBalanceText.setObjectName(_fromUtf8("sendBalanceText"))
        self.waitingTxsTable = QtGui.QTableView(self.sendTab)
        self.waitingTxsTable.setGeometry(QtCore.QRect(7, 240, 771, 261))
        self.waitingTxsTable.setStyleSheet(_fromUtf8(""))
        self.waitingTxsTable.setObjectName(_fromUtf8("waitingTxsTable"))
        self.sendBalanceText_2 = QtGui.QLabel(self.sendTab)
        self.sendBalanceText_2.setGeometry(QtCore.QRect(10, 210, 581, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sendBalanceText_2.setFont(font)
        self.sendBalanceText_2.setStyleSheet(_fromUtf8(""))
        self.sendBalanceText_2.setObjectName(_fromUtf8("sendBalanceText_2"))
        self.sendDescEdit = QtGui.QLineEdit(self.sendTab)
        self.sendDescEdit.setGeometry(QtCore.QRect(20, 60, 231, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sendDescEdit.setFont(font)
        self.sendDescEdit.setStyleSheet(_fromUtf8(""))
        self.sendDescEdit.setText(_fromUtf8(""))
        self.sendDescEdit.setObjectName(_fromUtf8("sendDescEdit"))
        self.tabWidget.addTab(self.sendTab, _fromUtf8(""))
        self.contactsTab = QtGui.QWidget()
        self.contactsTab.setObjectName(_fromUtf8("contactsTab"))
        self.contactsTableView = QtGui.QTableView(self.contactsTab)
        self.contactsTableView.setGeometry(QtCore.QRect(7, 10, 601, 481))
        self.contactsTableView.setStyleSheet(_fromUtf8(""))
        self.contactsTableView.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.contactsTableView.setAlternatingRowColors(True)
        self.contactsTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.contactsTableView.setTextElideMode(QtCore.Qt.ElideRight)
        self.contactsTableView.setObjectName(_fromUtf8("contactsTableView"))
        self.contactsTableView.horizontalHeader().setDefaultSectionSize(100)
        self.contactsTableView.horizontalHeader().setMinimumSectionSize(100)
        self.addContactButton = QtGui.QPushButton(self.contactsTab)
        self.addContactButton.setGeometry(QtCore.QRect(620, 20, 151, 41))
        self.addContactButton.setObjectName(_fromUtf8("addContactButton"))
        self.removeContactButton = QtGui.QPushButton(self.contactsTab)
        self.removeContactButton.setGeometry(QtCore.QRect(620, 70, 151, 41))
        self.removeContactButton.setObjectName(_fromUtf8("removeContactButton"))
        self.editContactButton = QtGui.QPushButton(self.contactsTab)
        self.editContactButton.setGeometry(QtCore.QRect(620, 120, 151, 41))
        self.editContactButton.setObjectName(_fromUtf8("editContactButton"))
        self.tabWidget.addTab(self.contactsTab, _fromUtf8(""))
        self.mineTab = QtGui.QWidget()
        self.mineTab.setObjectName(_fromUtf8("mineTab"))
        self.mineButton = QtGui.QPushButton(self.mineTab)
        self.mineButton.setGeometry(QtCore.QRect(550, 430, 221, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mineButton.setFont(font)
        self.mineButton.setStyleSheet(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/mineron/miner-on.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mineButton.setIcon(icon1)
        self.mineButton.setIconSize(QtCore.QSize(32, 32))
        self.mineButton.setObjectName(_fromUtf8("mineButton"))
        self.mineStatusText_2 = QtGui.QLabel(self.mineTab)
        self.mineStatusText_2.setGeometry(QtCore.QRect(10, 10, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.mineStatusText_2.setFont(font)
        self.mineStatusText_2.setStyleSheet(_fromUtf8("font: 25 14pt \"Ubuntu\";"))
        self.mineStatusText_2.setObjectName(_fromUtf8("mineStatusText_2"))
        self.label = QtGui.QLabel(self.mineTab)
        self.label.setGeometry(QtCore.QRect(10, 170, 301, 18))
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.mineTree = QtGui.QTreeWidget(self.mineTab)
        self.mineTree.setGeometry(QtCore.QRect(7, 200, 771, 221))
        self.mineTree.setStyleSheet(_fromUtf8(""))
        self.mineTree.setAnimated(True)
        self.mineTree.setExpandsOnDoubleClick(False)
        self.mineTree.setObjectName(_fromUtf8("mineTree"))
        self.mineTree.headerItem().setText(0, _fromUtf8("1"))
        self.mineTree.header().setCascadingSectionResizes(False)
        self.mineTree.header().setDefaultSectionSize(150)
        self.mineTree.header().setHighlightSections(False)
        self.mineTree.header().setMinimumSectionSize(100)
        self.mineTree.header().setStretchLastSection(False)
        self.mineStatusEdit = QtGui.QTextEdit(self.mineTab)
        self.mineStatusEdit.setGeometry(QtCore.QRect(10, 40, 761, 111))
        self.mineStatusEdit.setReadOnly(True)
        self.mineStatusEdit.setObjectName(_fromUtf8("mineStatusEdit"))
        self.mineClearButton = QtGui.QPushButton(self.mineTab)
        self.mineClearButton.setGeometry(QtCore.QRect(670, 160, 97, 27))
        self.mineClearButton.setObjectName(_fromUtf8("mineClearButton"))
        self.mineGenomeButton = QtGui.QPushButton(self.mineTab)
        self.mineGenomeButton.setGeometry(QtCore.QRect(610, 6, 161, 31))
        self.mineGenomeButton.setObjectName(_fromUtf8("mineGenomeButton"))
        self.tabWidget.addTab(self.mineTab, _fromUtf8(""))
        self.blockchain = QtGui.QWidget()
        self.blockchain.setObjectName(_fromUtf8("blockchain"))
        self.label_2 = QtGui.QLabel(self.blockchain)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.blockchain)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.blockchain)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 181, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.waitingTransactionsText = QtGui.QLabel(self.blockchain)
        self.waitingTransactionsText.setGeometry(QtCore.QRect(220, 60, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.waitingTransactionsText.setFont(font)
        self.waitingTransactionsText.setStyleSheet(_fromUtf8(""))
        self.waitingTransactionsText.setObjectName(_fromUtf8("waitingTransactionsText"))
        self.numberOfAuthoritiesText = QtGui.QLabel(self.blockchain)
        self.numberOfAuthoritiesText.setGeometry(QtCore.QRect(220, 110, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.numberOfAuthoritiesText.setFont(font)
        self.numberOfAuthoritiesText.setStyleSheet(_fromUtf8(""))
        self.numberOfAuthoritiesText.setObjectName(_fromUtf8("numberOfAuthoritiesText"))
        self.blockCountText = QtGui.QLabel(self.blockchain)
        self.blockCountText.setGeometry(QtCore.QRect(220, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.blockCountText.setFont(font)
        self.blockCountText.setStyleSheet(_fromUtf8(""))
        self.blockCountText.setObjectName(_fromUtf8("blockCountText"))
        self.blockchainLoadMoreButton = QtGui.QPushButton(self.blockchain)
        self.blockchainLoadMoreButton.setGeometry(QtCore.QRect(680, 480, 97, 27))
        self.blockchainLoadMoreButton.setStyleSheet(_fromUtf8(""))
        self.blockchainLoadMoreButton.setObjectName(_fromUtf8("blockchainLoadMoreButton"))
        self.blockchainTree = QtGui.QTreeWidget(self.blockchain)
        self.blockchainTree.setGeometry(QtCore.QRect(7, 160, 771, 311))
        self.blockchainTree.setStyleSheet(_fromUtf8(""))
        self.blockchainTree.setAnimated(True)
        self.blockchainTree.setExpandsOnDoubleClick(False)
        self.blockchainTree.setObjectName(_fromUtf8("blockchainTree"))
        self.blockchainTree.headerItem().setText(0, _fromUtf8("1"))
        self.blockchainTree.header().setCascadingSectionResizes(False)
        self.blockchainTree.header().setDefaultSectionSize(150)
        self.blockchainTree.header().setHighlightSections(False)
        self.blockchainTree.header().setMinimumSectionSize(100)
        self.blockchainTree.header().setStretchLastSection(False)
        self.tabWidget.addTab(self.blockchain, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuContacts = QtGui.QMenu(self.menubar)
        self.menuContacts.setObjectName(_fromUtf8("menuContacts"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionRestart = QtGui.QAction(MainWindow)
        self.actionRestart.setObjectName(_fromUtf8("actionRestart"))
        self.actionSave_Copy = QtGui.QAction(MainWindow)
        self.actionSave_Copy.setObjectName(_fromUtf8("actionSave_Copy"))
        self.actionNew_Contact = QtGui.QAction(MainWindow)
        self.actionNew_Contact.setObjectName(_fromUtf8("actionNew_Contact"))
        self.actionAddress = QtGui.QAction(MainWindow)
        self.actionAddress.setObjectName(_fromUtf8("actionAddress"))
        self.actionSeed = QtGui.QAction(MainWindow)
        self.actionSeed.setObjectName(_fromUtf8("actionSeed"))
        self.actionPublic_Keys = QtGui.QAction(MainWindow)
        self.actionPublic_Keys.setObjectName(_fromUtf8("actionPublic_Keys"))
        self.actionExport_History = QtGui.QAction(MainWindow)
        self.actionExport_History.setObjectName(_fromUtf8("actionExport_History"))
        self.actionSign_Verify_Message = QtGui.QAction(MainWindow)
        self.actionSign_Verify_Message.setObjectName(_fromUtf8("actionSign_Verify_Message"))
        self.actionEncrpyt_Decyrpt_Message = QtGui.QAction(MainWindow)
        self.actionEncrpyt_Decyrpt_Message.setObjectName(_fromUtf8("actionEncrpyt_Decyrpt_Message"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOfficial_Website = QtGui.QAction(MainWindow)
        self.actionOfficial_Website.setObjectName(_fromUtf8("actionOfficial_Website"))
        self.menuFile.addAction(self.actionRestart)
        self.menuFile.addAction(self.actionSave_Copy)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuContacts.addAction(self.actionNew_Contact)
        self.menuContacts.addSeparator()
        self.menuContacts.addAction(self.actionAddress)
        self.menuContacts.addAction(self.actionSeed)
        self.menuContacts.addAction(self.actionPublic_Keys)
        self.menuContacts.addSeparator()
        self.menuContacts.addAction(self.actionExport_History)
        self.menuTools.addAction(self.actionSign_Verify_Message)
        self.menuTools.addAction(self.actionEncrpyt_Decyrpt_Message)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionOfficial_Website)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuContacts.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_5.setText(_translate("MainWindow", "Address", None))
        self.infoAddressText.setText(_translate("MainWindow", "TextLabel", None))
        self.label_7.setText(_translate("MainWindow", "Balance", None))
        self.infoBalanceText.setText(_translate("MainWindow", "TextLabel", None))
        self.label_9.setText(_translate("MainWindow", "Total Mine Value", None))
        self.infoMineText.setText(_translate("MainWindow", "TextLabel", None))
        self.label_11.setText(_translate("MainWindow", "Total Spent Coins", None))
        self.infoSpendText.setText(_translate("MainWindow", "TextLabel", None))
        self.infoReceivedText.setText(_translate("MainWindow", "TextLabel", None))
        self.label_14.setText(_translate("MainWindow", "Total Received Coins", None))
        self.label_15.setText(_translate("MainWindow", "Transaction History", None))
        self.infoFilterButton.setText(_translate("MainWindow", "Filter", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoTab), _translate("MainWindow", "Info", None))
        self.sendButton.setText(_translate("MainWindow", "Send", None))
        self.sendAddressEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Coins</p></body></html>", None))
        self.sendAddressEdit.setPlaceholderText(_translate("MainWindow", "Address", None))
        self.sendCoinsEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Coins</p></body></html>", None))
        self.sendCoinsEdit.setPlaceholderText(_translate("MainWindow", "Coins", None))
        self.sendBalanceLabel.setText(_translate("MainWindow", "Your Balance: ", None))
        self.sendBalanceText.setText(_translate("MainWindow", "Your Balance: ", None))
        self.sendBalanceText_2.setText(_translate("MainWindow", "Your waiting Transactions", None))
        self.sendDescEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Coins</p></body></html>", None))
        self.sendDescEdit.setPlaceholderText(_translate("MainWindow", "Description", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sendTab), _translate("MainWindow", "Send", None))
        self.addContactButton.setText(_translate("MainWindow", "Add", None))
        self.removeContactButton.setText(_translate("MainWindow", "Remove", None))
        self.editContactButton.setText(_translate("MainWindow", "Edit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contactsTab), _translate("MainWindow", "Contacts", None))
        self.mineButton.setText(_translate("MainWindow", "Start Mining", None))
        self.mineStatusText_2.setText(_translate("MainWindow", "Status:", None))
        self.label.setText(_translate("MainWindow", "Blocks that are mined by you", None))
        self.mineClearButton.setText(_translate("MainWindow", "Clear", None))
        self.mineGenomeButton.setText(_translate("MainWindow", "Reference Genome", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mineTab), _translate("MainWindow", "Mine", None))
        self.label_2.setText(_translate("MainWindow", "Block Count", None))
        self.label_3.setText(_translate("MainWindow", "Waiting Transactions", None))
        self.label_4.setText(_translate("MainWindow", "Number of Authorities", None))
        self.waitingTransactionsText.setText(_translate("MainWindow", "0", None))
        self.numberOfAuthoritiesText.setText(_translate("MainWindow", "0", None))
        self.blockCountText.setText(_translate("MainWindow", "0", None))
        self.blockchainLoadMoreButton.setText(_translate("MainWindow", "Load More", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.blockchain), _translate("MainWindow", "Blockchain", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuContacts.setTitle(_translate("MainWindow", "Wallet", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen.setText(_translate("MainWindow", "Open Wallet", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionRestart.setText(_translate("MainWindow", "Restart", None))
        self.actionSave_Copy.setText(_translate("MainWindow", "Save Copy", None))
        self.actionNew_Contact.setText(_translate("MainWindow", "New Contact", None))
        self.actionAddress.setText(_translate("MainWindow", "Address", None))
        self.actionSeed.setText(_translate("MainWindow", "Seed", None))
        self.actionPublic_Keys.setText(_translate("MainWindow", "Public Key", None))
        self.actionExport_History.setText(_translate("MainWindow", "Export History", None))
        self.actionSign_Verify_Message.setText(_translate("MainWindow", "Sign/Verify Message", None))
        self.actionEncrpyt_Decyrpt_Message.setText(_translate("MainWindow", "Encrpyt/Decyrpt Message", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionOfficial_Website.setText(_translate("MainWindow", "Official Website", None))

import icons_rc
